kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: kafkadeployment
  namespace: dev
  labels:
    app: kafkatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkatest
  template:
    metadata:
      labels:
        app: kafkatest
    spec:
      containers:
        - name: kafkatest
          image: docker.io/abbiee9/kafkatest:v1
          ports:
          - name: nfs
            containerPort: 8500
            protocol: TCP
          env:
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: mongodb-kafka-connection-details
                  key: mongo.user
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: mongodb-kafka-connection-details
                  key: mongo.password
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: mongodb-kafka-connection-details
                  key: mongo.uri
            - name: spring.cloud.stream.kafka.binder.brokers
              valueFrom:
                secretKeyRef:
                  name: mongodb-kafka-connection-details
                  key:  kafka.broker