spring:
  application:
    name: KafkaTest
  cloud:
    stream:
      kafka:
        binder: 
          auto-create-topics: true
          
      bindings:
        output: 
          destination: outputtopic
          content-type: application/json 
 
   
     
server:
  port: 8500


  
